config/routes.rb
Board::Application.routes.draw do

  Rails.application.routes.draw do
    filter :locale
  end

  namespace :dashboard do
      resources :items do
        resources :messages
        resources :tags
        resources :photos
      end
  end

  devise_for :users

  
  resources :tags
  

  root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  
  attr_accessible :description, :title, :contact_phone, :contact_name, :state, :sold_at, :photos_attributes, :main_photo_id

  belongs_to :user
  has_many :messages
  has_many :photos, :dependent => :destroy
  has_one :main_photo
  accepts_nested_attributes_for :photos, :allow_destroy => true
  has_and_belongs_to_many :tags, uniq: true
  
  validates :title, :presence => true
  validates :title, :length => {:in => 3..255}
  validates_associated :tags
  validates :contact_phone, :presence => true
  validates :contact_name, :presence => true

  state_machine :initial => :hidden do
    after_transition any - :sold => :sold, :do => :set_sale_date_time

    event :publish do
      transition :hidden => :published
    end

    event :sell do
      transition :hidden => :sold
      transition :published => :sold
    end

    event :hide do
      transition :published => :hidden
    end

    state :hidden, :sold do
      def visible?
        false
      end
    end

    state :published do
      def visible?
        true
      end
    end
  end

  #adds tags to an item
  def set_tags(tags)
    if Tag.tags_are_valid? tags
      self.tags = []
      Tag.split_tags(tags).each do |tag|
        self.tags << Tag.where(tag: tag).first_or_create
      end
    end
  end

  #sets item sale date
  def set_sale_date_time
    @sold_at = Time.new
  end

  def set_main_photo (id)
    self.main_photo_id = id
    self.save
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :item
  belongs_to :user

  attr_accessible :body, :subject
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :item
  attr_accessible :photo
  mount_uploader :photo, PhotosUploader

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :description, :tag

  has_and_belongs_to_many :items, uniq: true
  
  validates :tag, :uniqueness => { :case_sensitive => false }

  #checks if tags is an array or a string that can be converted to an array using ,
  def self.tags_are_valid?(tags)
    unless tags.is_a?(Array)
      tags = split_tags(tags)
      tags.kind_of?(Array)
    else
      true
    end
  end
  
  #splits and remove spaces form line of tags
  def self.split_tags(tags)
    _tags = []
    tags.split(',').each do |tag|
      _tags << tag.strip!
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :items, dependent: :destroy
  has_many :messages
  
  validates :email, :uniqueness => { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_filter :set_locale
  
  protect_from_forgery

  def set_locale
    if (params[:locale])
      I18n.locale = params[:locale]
    else
      locale = request.preferred_language_from(I18n.available_locales)
      unless locale
        locale = I18n.default_locale
      end
      redirect_to url_for locale: locale
    end
  end
  
  
  def default_url_options(options={})
    { :locale => I18n.locale }
  end
  
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ApplicationController

  before_filter :authenticate_user!

end

app/controllers/dashboard/items_controller.rb
class Dashboard::ItemsController < Dashboard::ApplicationController
  def index
    @items = current_user.items.all
  end

  def show
    @item = current_user.items.find(params[:id])
    @photos = @item.photos
  end

  def new
    @item = Item.new
    @item.photos.build
  end

  def edit
    @item = current_user.items.find(params[:id])
    @item.photos.build
  end

  def create
    @item = current_user.items.build(params[:item])
    #@item.photos.build
    
    if @item.save
      @item.set_tags(params[:tags])

      if @item.photos.last.id && params[:item][:main_photo_id] == 'new'
        @item.set_main_photo(@item.photos.last.id)
      end

      redirect_to dashboard_item_path(@item), notice: t('item.notice.saved')
    else
      render action: "new"
    end
  end

  def update
    @item = current_user.items.find(params[:id])

    if @item.update_attributes(params[:item])
      @item.set_tags(params[:tags])

      if params[:item][:main_photo_id] == 'new'
        @item.set_main_photo(@item.photos.last.id)
      else
        @item.set_main_photo(params[:item][:main_photo_id])
      end

      redirect_to dashboard_item_path(@item), notice: t('item.notice.updated')
    else
      render action: "edit"
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy

    redirect_to dashboard_items_url, notice: t('item.notice.deleted')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_items_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def item_state_select(form, item)
    form.select :state, options_from_collection_for_select(Item.state_machine.states.map(&:name), "to_s", "to_s", item.state)
  end
end

app/views/dashboard/items/_form.html.haml
= form_for @item, as: :item, url: @item.new_record? ? dashboard_items_path : dashboard_item_path(@item), :html => {:multipart => true} do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= t "item.error.form"
      / "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg
  #title
    %b= f.label :title
    = f.text_field :title
  
  #description
    %b= f.label :description
    %br
    = f.text_area :description
  
  #photos
    = f.fields_for :photos do |photo|
      - if photo.object.new_record?
        = f.radio_button :main_photo_id, 'new'
        = photo.file_field :photo
      - else
        = f.radio_button :main_photo_id, photo.object.id
        = image_tag(photo.object.photo.url(:thumb))
        = photo.check_box :_destroy
      %br

  #contact_phone
    %b= f.label :contact_phone
    = f.text_field :contact_phone

  #contact_name
    %b= f.label :contact_name
    = f.text_field :contact_name

  #state
    - if @item.new_record?
      = check_box_tag 'item[state]', :published
      %b= label_tag t(:publish, :scope => [:activerecord, :state_machines, :item, :events])
    - else
      %b= f.label :state
      = item_state_select f, @item

  #tags
    %b= f.label :tags
    = text_field_tag :tags, f.object.tags.collect(&:tag).join(", ")

  .actions
    = f.submit t('button.save')

app/views/dashboard/items/edit.html.haml
%h1= t 'item.title.edit'

= render 'form'

= link_to t('item.link.show'), dashboard_item_path(@item)
\|
= link_to t('item.link.back'), dashboard_items_path

app/views/dashboard/items/index.html.haml
%h1
  = t 'item.title.list'

%table
  %tr
    %th= Item.human_attribute_name(:title)
    %th
    %th= Item.human_attribute_name(:created_at)
    %th= Item.human_attribute_name(:contact_name)
    %th= Item.human_attribute_name(:contact_phone)
    %th= Item.human_attribute_name(:state)
    %th
    %th

  - @items.each do |item|
    %tr
      %td
        %b= link_to item.title, dashboard_item_path(item)
      %td= #item.image goes here
      %td= l item.created_at, :format => :full
      %td= item.contact_name
      %td= item.contact_phone
      %td= t (item.state.present? ? item.state.to_s : :hidden), :scope => [:activerecord, :state_machines, :item, :states]
      %td= link_to t('item.link.edit'), edit_dashboard_item_path(item)
      %td= link_to t('item.link.delete'), dashboard_item_path(item), method: :delete, data: { confirm: t('item.warning.delete') }

%br

= link_to link_to t('item.link.new'), new_dashboard_item_path

app/views/dashboard/items/new.html.haml
%h1= t 'item.title.new'

= render 'form'

= link_to t('item.link.back'), dashboard_items_path

app/views/dashboard/items/show.html.haml
- scope = {:scope => [:activerecord, :attributes, :item]}

#title 
  %b
    = label_tag t :title, scope
    \:
  = @item.title

#description
  %b
    = label_tag t :description, scope
    \:
  = @item.description

#photos
  - @item.photos.each do |photo|
    = link_to(image_tag(photo.photo.url(:thumb)), photo.photo.url)
    %br

#contact_phone
  %b
    = label_tag t :contact_phone, scope
    \:
  = @item.contact_phone

#contact_name
  %b
    = label_tag t :contact_name, scope
    \:
  = @item.contact_name

#state
  %b
    = label_tag t :state, scope
    \:
  = t @item.state, :scope => [:activerecord, :state_machines, :item, :states]

#tags
  %b
    = label_tag t :tags, scope
    \:
  = @item.tags.collect(&:tag).join(", ")


= link_to t('item.link.edit'), edit_dashboard_item_path(@item)
\|
= link_to t('item.link.back'), dashboard_items_path

app/views/home/index.html.erb
Welcome!

app/views/home/index.html.haml
%h1
  = t :welcome
%br
= link_to t('item.link.my_items'), dashboard_items_path

app/views/layouts/application.html.haml
%html
  %head
    %title 
      = t :page_title
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    #auth_status
      - if current_user
        = link_to current_user.email, edit_user_registration_path(current_user)
        |
        = link_to t('link.exit'), destroy_user_session_path, method: :delete
      - else
        = link_to t('link.enter'), new_user_session_path
        |
        = link_to t('link.signup'), new_user_registration_path
      - 10.times do
        = '&nbsp'.html_safe
      = link_to 'RU', url_for(:locale => 'ru')
      |
      = link_to 'EN', url_for(:locale => 'en')

    #flashing
      - for type, message in flash
        .flash(class="#{type}")= message

    = yield